import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import "@/styles/globals.scss";

const inter = Space_Grotesk({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Test task",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>{children}</body>
        </html>
    );
}
